/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.paneles;

/**
 *
 * @author vehuiah
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicio
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformativo = new javax.swing.JPanel();
        PanelCapitalNeto = new javax.swing.JPanel();
        PanelCapitalGanado = new javax.swing.JPanel();
        PanelPerdidas = new javax.swing.JPanel();
        PanelNovedadesMercado = new javax.swing.JPanel();
        panelTareas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelOrdenes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaOrdenesenCompra = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(37, 43, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInformativo.setBackground(new java.awt.Color(47, 54, 64));
        panelInformativo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout PanelCapitalNetoLayout = new javax.swing.GroupLayout(PanelCapitalNeto);
        PanelCapitalNeto.setLayout(PanelCapitalNetoLayout);
        PanelCapitalNetoLayout.setHorizontalGroup(
            PanelCapitalNetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        PanelCapitalNetoLayout.setVerticalGroup(
            PanelCapitalNetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        panelInformativo.add(PanelCapitalNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 35, 300, 230));

        PanelCapitalGanado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));
        PanelCapitalGanado.setAlignmentX(1.0F);
        PanelCapitalGanado.setAlignmentY(2.0F);

        javax.swing.GroupLayout PanelCapitalGanadoLayout = new javax.swing.GroupLayout(PanelCapitalGanado);
        PanelCapitalGanado.setLayout(PanelCapitalGanadoLayout);
        PanelCapitalGanadoLayout.setHorizontalGroup(
            PanelCapitalGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        PanelCapitalGanadoLayout.setVerticalGroup(
            PanelCapitalGanadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        panelInformativo.add(PanelCapitalGanado, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 35, 300, 230));

        javax.swing.GroupLayout PanelPerdidasLayout = new javax.swing.GroupLayout(PanelPerdidas);
        PanelPerdidas.setLayout(PanelPerdidasLayout);
        PanelPerdidasLayout.setHorizontalGroup(
            PanelPerdidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        PanelPerdidasLayout.setVerticalGroup(
            PanelPerdidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        panelInformativo.add(PanelPerdidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 35, 300, 230));

        javax.swing.GroupLayout PanelNovedadesMercadoLayout = new javax.swing.GroupLayout(PanelNovedadesMercado);
        PanelNovedadesMercado.setLayout(PanelNovedadesMercadoLayout);
        PanelNovedadesMercadoLayout.setHorizontalGroup(
            PanelNovedadesMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );
        PanelNovedadesMercadoLayout.setVerticalGroup(
            PanelNovedadesMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        panelInformativo.add(PanelNovedadesMercado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 35, 325, 230));

        add(panelInformativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 299));

        panelTareas.setBackground(new java.awt.Color(47, 54, 64));
        panelTareas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        panelTareas.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 35, 410, 230));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        panelTareas.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 35, 410, 230));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        panelTareas.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 35, 410, 230));

        add(panelTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1350, 299));

        panelOrdenes.setBackground(new java.awt.Color(47, 54, 64));
        panelOrdenes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaOrdenesenCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaOrdenesenCompra.setRowHeight(20);
        jScrollPane1.setViewportView(TablaOrdenesenCompra);

        panelOrdenes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 35, 625, 230));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        panelOrdenes.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 35, 625, 230));

        add(panelOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1350, 299));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCapitalGanado;
    private javax.swing.JPanel PanelCapitalNeto;
    private javax.swing.JPanel PanelNovedadesMercado;
    private javax.swing.JPanel PanelPerdidas;
    private javax.swing.JTable TablaOrdenesenCompra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel panelInformativo;
    private javax.swing.JPanel panelOrdenes;
    private javax.swing.JPanel panelTareas;
    // End of variables declaration//GEN-END:variables
}
