/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.paneles;

/**
 *
 * @author vehuiah
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicio
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloInicio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelRefinadoInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelCraftInfo = new javax.swing.JPanel();
        panelRefinadoInfo1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelMercadoInfo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(37, 43, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloInicio.setForeground(new java.awt.Color(200, 155, 60));
        lblTituloInicio.setText("INICIO");
        add(lblTituloInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 300, 40));

        jLabel1.setForeground(new java.awt.Color(220, 220, 220));
        jLabel1.setText("Resumen general del sistema");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        panelRefinadoInfo.setBackground(new java.awt.Color(47, 54, 64));

        jLabel2.setForeground(new java.awt.Color(200, 155, 60));
        jLabel2.setText("REFINADO");

        javax.swing.GroupLayout panelRefinadoInfoLayout = new javax.swing.GroupLayout(panelRefinadoInfo);
        panelRefinadoInfo.setLayout(panelRefinadoInfoLayout);
        panelRefinadoInfoLayout.setHorizontalGroup(
            panelRefinadoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRefinadoInfoLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panelRefinadoInfoLayout.setVerticalGroup(
            panelRefinadoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRefinadoInfoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        add(panelRefinadoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 250, 140));

        panelCraftInfo.setBackground(new java.awt.Color(47, 54, 64));

        panelRefinadoInfo1.setBackground(new java.awt.Color(47, 54, 64));

        jLabel5.setForeground(new java.awt.Color(200, 155, 60));
        jLabel5.setText("CRAFT");

        javax.swing.GroupLayout panelRefinadoInfo1Layout = new javax.swing.GroupLayout(panelRefinadoInfo1);
        panelRefinadoInfo1.setLayout(panelRefinadoInfo1Layout);
        panelRefinadoInfo1Layout.setHorizontalGroup(
            panelRefinadoInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRefinadoInfo1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel5)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panelRefinadoInfo1Layout.setVerticalGroup(
            panelRefinadoInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRefinadoInfo1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCraftInfoLayout = new javax.swing.GroupLayout(panelCraftInfo);
        panelCraftInfo.setLayout(panelCraftInfoLayout);
        panelCraftInfoLayout.setHorizontalGroup(
            panelCraftInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(panelCraftInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCraftInfoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRefinadoInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelCraftInfoLayout.setVerticalGroup(
            panelCraftInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(panelCraftInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCraftInfoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRefinadoInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(panelCraftInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 250, 140));

        panelMercadoInfo.setBackground(new java.awt.Color(47, 54, 64));

        jLabel4.setForeground(new java.awt.Color(200, 155, 60));
        jLabel4.setText("MERCADO");

        javax.swing.GroupLayout panelMercadoInfoLayout = new javax.swing.GroupLayout(panelMercadoInfo);
        panelMercadoInfo.setLayout(panelMercadoInfoLayout);
        panelMercadoInfoLayout.setHorizontalGroup(
            panelMercadoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMercadoInfoLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel4)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panelMercadoInfoLayout.setVerticalGroup(
            panelMercadoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMercadoInfoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        add(panelMercadoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 250, 140));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblTituloInicio;
    private javax.swing.JPanel panelCraftInfo;
    private javax.swing.JPanel panelMercadoInfo;
    private javax.swing.JPanel panelRefinadoInfo;
    private javax.swing.JPanel panelRefinadoInfo1;
    // End of variables declaration//GEN-END:variables
}
