/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.paneles;

/**
 *
 * @author vehuiah
 */
public class PanelCraft extends javax.swing.JPanel {

    /**
     * Creates new form PanelCraft
     */
    public PanelCraft() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloRefinado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(37, 43, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloRefinado.setForeground(new java.awt.Color(200, 155, 60));
        lblTituloRefinado.setText("Craft");
        add(lblTituloRefinado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTituloRefinado;
    // End of variables declaration//GEN-END:variables
}
