/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.paneles;

/**
 *
 * @author vehuiah
 */
public class PanelMercado extends javax.swing.JPanel {

    /**
     * Creates new form PanelMercado
     */
    public PanelMercado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelColaFabricacion = new javax.swing.JPanel();
        lblTituloCola = new javax.swing.JLabel();
        scrollColaFabricacion = new javax.swing.JScrollPane();
        panelContenidoCola = new javax.swing.JPanel();
        panelListaCompras = new javax.swing.JPanel();
        panelOrdenesMercado = new javax.swing.JPanel();
        panelAuditoriaCapital = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(37, 43, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelColaFabricacion.setBackground(new java.awt.Color(47, 54, 64));
        panelColaFabricacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloCola.setForeground(new java.awt.Color(230, 230, 230));
        lblTituloCola.setText("COLA DE FABRICACIÓN");
        panelColaFabricacion.add(lblTituloCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 250, 30));

        scrollColaFabricacion.setViewportView(panelContenidoCola);

        panelContenidoCola.setBackground(new java.awt.Color(30, 34, 43));
        panelContenidoCola.setLayout(new javax.swing.BoxLayout(panelContenidoCola, javax.swing.BoxLayout.LINE_AXIS));
        scrollColaFabricacion.setViewportView(panelContenidoCola);

        panelColaFabricacion.add(scrollColaFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, 810));

        jPanel1.add(panelColaFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 880));

        javax.swing.GroupLayout panelListaComprasLayout = new javax.swing.GroupLayout(panelListaCompras);
        panelListaCompras.setLayout(panelListaComprasLayout);
        panelListaComprasLayout.setHorizontalGroup(
            panelListaComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panelListaComprasLayout.setVerticalGroup(
            panelListaComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jPanel1.add(panelListaCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 1020, 520));

        javax.swing.GroupLayout panelOrdenesMercadoLayout = new javax.swing.GroupLayout(panelOrdenesMercado);
        panelOrdenesMercado.setLayout(panelOrdenesMercadoLayout);
        panelOrdenesMercadoLayout.setHorizontalGroup(
            panelOrdenesMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        panelOrdenesMercadoLayout.setVerticalGroup(
            panelOrdenesMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jPanel1.add(panelOrdenesMercado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 570, 350));

        javax.swing.GroupLayout panelAuditoriaCapitalLayout = new javax.swing.GroupLayout(panelAuditoriaCapital);
        panelAuditoriaCapital.setLayout(panelAuditoriaCapitalLayout);
        panelAuditoriaCapitalLayout.setHorizontalGroup(
            panelAuditoriaCapitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        panelAuditoriaCapitalLayout.setVerticalGroup(
            panelAuditoriaCapitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jPanel1.add(panelAuditoriaCapital, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, 440, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTituloCola;
    private javax.swing.JPanel panelAuditoriaCapital;
    private javax.swing.JPanel panelColaFabricacion;
    private javax.swing.JPanel panelContenidoCola;
    private javax.swing.JPanel panelListaCompras;
    private javax.swing.JPanel panelOrdenesMercado;
    private javax.swing.JScrollPane scrollColaFabricacion;
    // End of variables declaration//GEN-END:variables
}
