/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas.paneles;

/**
 *
 * @author vehuiah
 */
public class PanelRefinado extends javax.swing.JPanel {

    /**
     * Creates new form PanelRefinado
     */
    public PanelRefinado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloVentas = new javax.swing.JLabel();
        panelPlataTotal = new javax.swing.JPanel();
        panelEstadisticas = new javax.swing.JPanel();
        panelOrdenesActivas = new javax.swing.JPanel();
        panelProfitTotal = new javax.swing.JPanel();
        panelUnidadesVendidas = new javax.swing.JPanel();
        panelCapitalRecuperado = new javax.swing.JPanel();
        scrollVentas = new javax.swing.JScrollPane();
        panelContenidoVentas = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(30, 34, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloVentas.setText("ÓRDENES DE VENTA");
        jPanel1.add(lblTituloVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 700, 60));

        javax.swing.GroupLayout panelPlataTotalLayout = new javax.swing.GroupLayout(panelPlataTotal);
        panelPlataTotal.setLayout(panelPlataTotalLayout);
        panelPlataTotalLayout.setHorizontalGroup(
            panelPlataTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        panelPlataTotalLayout.setVerticalGroup(
            panelPlataTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(panelPlataTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 290, 80));

        panelEstadisticas.setBackground(new java.awt.Color(47, 54, 64));
        panelEstadisticas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panelOrdenesActivasLayout = new javax.swing.GroupLayout(panelOrdenesActivas);
        panelOrdenesActivas.setLayout(panelOrdenesActivasLayout);
        panelOrdenesActivasLayout.setHorizontalGroup(
            panelOrdenesActivasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        panelOrdenesActivasLayout.setVerticalGroup(
            panelOrdenesActivasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelEstadisticas.add(panelOrdenesActivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 317, 100));

        javax.swing.GroupLayout panelProfitTotalLayout = new javax.swing.GroupLayout(panelProfitTotal);
        panelProfitTotal.setLayout(panelProfitTotalLayout);
        panelProfitTotalLayout.setHorizontalGroup(
            panelProfitTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        panelProfitTotalLayout.setVerticalGroup(
            panelProfitTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelEstadisticas.add(panelProfitTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 0, 317, 100));

        javax.swing.GroupLayout panelUnidadesVendidasLayout = new javax.swing.GroupLayout(panelUnidadesVendidas);
        panelUnidadesVendidas.setLayout(panelUnidadesVendidasLayout);
        panelUnidadesVendidasLayout.setHorizontalGroup(
            panelUnidadesVendidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        panelUnidadesVendidasLayout.setVerticalGroup(
            panelUnidadesVendidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelEstadisticas.add(panelUnidadesVendidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 0, 317, 100));

        javax.swing.GroupLayout panelCapitalRecuperadoLayout = new javax.swing.GroupLayout(panelCapitalRecuperado);
        panelCapitalRecuperado.setLayout(panelCapitalRecuperadoLayout);
        panelCapitalRecuperadoLayout.setHorizontalGroup(
            panelCapitalRecuperadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
        panelCapitalRecuperadoLayout.setVerticalGroup(
            panelCapitalRecuperadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelEstadisticas.add(panelCapitalRecuperado, new org.netbeans.lib.awtextra.AbsoluteConstraints(951, 0, 319, 100));

        jPanel1.add(panelEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 1270, 100));

        panelContenidoVentas.setLayout(new java.awt.GridLayout(0, 4, 15, 15));
        scrollVentas.setViewportView(panelContenidoVentas);

        jPanel1.add(scrollVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 1270, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTituloVentas;
    private javax.swing.JPanel panelCapitalRecuperado;
    private javax.swing.JPanel panelContenidoVentas;
    private javax.swing.JPanel panelEstadisticas;
    private javax.swing.JPanel panelOrdenesActivas;
    private javax.swing.JPanel panelPlataTotal;
    private javax.swing.JPanel panelProfitTotal;
    private javax.swing.JPanel panelUnidadesVendidas;
    private javax.swing.JScrollPane scrollVentas;
    // End of variables declaration//GEN-END:variables
}
