
/*
 * @author vehuiah
 */
import Paneles.Inventario;

public class VentanaPrincipal extends javax.swing.JFrame {

    public VentanaPrincipal() {
        initComponents();
    }
   



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnInventario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        INICIO2 = new javax.swing.JButton();
        btnCrafteo = new javax.swing.JButton();
        INICIO4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PanelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(7, 11, 15));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(11, 15, 21));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(20, 24, 30), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1598, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 100));

        jPanel3.setBackground(new java.awt.Color(2, 6, 24));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 33, 20), 2, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInventario.setText("INVENTARIO");
        btnInventario.addActionListener(this::btnInventarioActionPerformed);
        jPanel3.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 160, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGO");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 120));

        btnInicio.setText("INICIO");
        btnInicio.addActionListener(this::btnInicioActionPerformed);
        jPanel3.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 160, -1));

        INICIO2.setText("ORDEN DE VENTAS");
        INICIO2.addActionListener(this::INICIO2ActionPerformed);
        jPanel3.add(INICIO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 160, -1));

        btnCrafteo.setText("CRAFTEO");
        btnCrafteo.addActionListener(this::btnCrafteoActionPerformed);
        jPanel3.add(btnCrafteo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, -1));

        INICIO4.setText("ORDEN DE COMPRA");
        INICIO4.addActionListener(this::INICIO4ActionPerformed);
        jPanel3.add(INICIO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, -1));

        jButton1.setText("GESTION DE PRECIOS");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 160, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 99, 200, 900));

        PanelContenido.setBackground(new java.awt.Color(7, 11, 14));
        PanelContenido.setLayout(new java.awt.BorderLayout());
        jPanel1.add(PanelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 1400, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
 Inventario panelInventario = new Inventario();
    
    // Definir manualmente la posición (0,0) y el tamaño exacto
    panelInventario.setBounds(0, 0, 1400, 800);
    
    PanelContenido.removeAll();
    PanelContenido.add(panelInventario); // Sin BorderLayout
    
    PanelContenido.revalidate();
    PanelContenido.repaint();
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void INICIO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INICIO2ActionPerformed

    private void btnCrafteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrafteoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrafteoActionPerformed

    private void INICIO4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIO4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INICIO4ActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INICIO2;
    private javax.swing.JButton INICIO4;
    private javax.swing.JPanel PanelContenido;
    private javax.swing.JButton btnCrafteo;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
// Pon esto justo antes de la última llave '}' de tu archivo
    public static void main(String args[]) {
        /* Configura el diseño de la interfaz (opcional, busca el look and feel del sistema) */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Crea y muestra la ventana */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaPrincipal().setVisible(true);
        });
    }


}
