/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author vehuiah
 */

import Vistas.paneles.PanelInicio;
import Vistas.paneles.PanelRefinado;
import Vistas.paneles.PanelCraft;
import Vistas.paneles.PanelMercado;
import Vistas.paneles.PanelConfiguracion;






public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarPanel(new PanelInicio());
    }

    
    
      private void mostrarPanel(javax.swing.JPanel panel) {

    panel.setSize(panelContenido.getWidth(), panelContenido.getHeight());

    panelContenido.removeAll();

    panelContenido.add(panel, java.awt.BorderLayout.CENTER);

    panelContenido.revalidate();

    panelContenido.repaint();

}
  
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        panelLinea = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnRefinado = new javax.swing.JButton();
        btnCraft = new javax.swing.JButton();
        btnMercado = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        lblVersion = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AlbionVehuiah");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(37, 43, 51));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(27, 31, 36));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setBackground(new java.awt.Color(200, 155, 60));
        lblLogo.setForeground(new java.awt.Color(200, 155, 60));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("ALBION VEHUIAH");
        panelMenu.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 30, 210, 50));

        panelLinea.setBackground(new java.awt.Color(200, 155, 60));

        javax.swing.GroupLayout panelLineaLayout = new javax.swing.GroupLayout(panelLinea);
        panelLinea.setLayout(panelLineaLayout);
        panelLineaLayout.setHorizontalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        panelLineaLayout.setVerticalGroup(
            panelLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        panelMenu.add(panelLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 95, 180, 2));

        btnInicio.setBackground(new java.awt.Color(200, 155, 60));
        btnInicio.setForeground(new java.awt.Color(20, 20, 20));
        btnInicio.setText("INICIO");
        btnInicio.addActionListener(this::btnInicioActionPerformed);
        panelMenu.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 140, 200, 45));

        btnRefinado.setBackground(new java.awt.Color(47, 54, 64));
        btnRefinado.setForeground(new java.awt.Color(234, 234, 234));
        btnRefinado.setText("REFINADO");
        btnRefinado.addActionListener(this::btnRefinadoActionPerformed);
        panelMenu.add(btnRefinado, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 195, 200, 45));

        btnCraft.setBackground(new java.awt.Color(47, 54, 64));
        btnCraft.setForeground(new java.awt.Color(234, 234, 234));
        btnCraft.setText("CRAFT");
        btnCraft.addActionListener(this::btnCraftActionPerformed);
        panelMenu.add(btnCraft, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 250, 200, 45));

        btnMercado.setBackground(new java.awt.Color(47, 54, 64));
        btnMercado.setForeground(new java.awt.Color(234, 234, 234));
        btnMercado.setText("MERCADO");
        btnMercado.addActionListener(this::btnMercadoActionPerformed);
        panelMenu.add(btnMercado, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 305, 200, 45));

        btnConfiguracion.setBackground(new java.awt.Color(47, 54, 64));
        btnConfiguracion.setForeground(new java.awt.Color(234, 234, 234));
        btnConfiguracion.setText("CONFIGURACION");
        btnConfiguracion.addActionListener(this::btnConfiguracionActionPerformed);
        panelMenu.add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 360, 200, 45));

        lblVersion.setBackground(new java.awt.Color(120, 120, 120));
        lblVersion.setForeground(new java.awt.Color(120, 120, 120));
        lblVersion.setText("AlbionVehuiah v0.1");
        panelMenu.add(lblVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 850, -1, -1));

        panelPrincipal.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 900));

        panelContenido.setBackground(new java.awt.Color(37, 43, 51));
        panelContenido.setLayout(new java.awt.BorderLayout());
        panelPrincipal.add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1350, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
     mostrarPanel(new PanelInicio());   // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnRefinadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefinadoActionPerformed
mostrarPanel(new PanelRefinado());        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefinadoActionPerformed

    private void btnCraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCraftActionPerformed
mostrarPanel(new PanelCraft());        // TODO add your handling code here:
    }//GEN-LAST:event_btnCraftActionPerformed

    private void btnMercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMercadoActionPerformed
mostrarPanel(new PanelMercado());        // TODO add your handling code here:
    }//GEN-LAST:event_btnMercadoActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
    mostrarPanel(new PanelConfiguracion());        // TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnCraft;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMercado;
    private javax.swing.JButton btnRefinado;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelLinea;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
